frontend :
  image : bench
  volumes :
    - ~/work/github/mongo-mysql-bench:/usr/local/app
  links :
    - mongo
    - mysql
  ports:
    - "3000:3000"
mongo :
  image : mongo
  ports:
    - "27017:27017"
  command: --smallfiles
mysql :
  image : mysql
  environment:
      MYSQL_ROOT_PASSWORD: "123"
  ports:
    - "3306:3306"
